# Generated by Django 4.2.17 on 2025-03-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyserver_getcheesy', '0004_alter_cheesyjoke_repeat_interval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheesyjoke',
            name='repeat_interval',
        ),
        migrations.RemoveField(
            model_name='cheesyquote',
            name='repeat_interval',
        ),
        migrations.RemoveField(
            model_name='compliment',
            name='repeat_interval',
        ),
        migrations.AddField(
            model_name='cheesyjoke',
            name='repeat_interval_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cheesyjoke',
            name='repeat_interval_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cheesyjoke',
            name='repeat_interval_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cheesyjoke',
            name='repeat_interval_weeks',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cheesyquote',
            name='repeat_interval_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cheesyquote',
            name='repeat_interval_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cheesyquote',
            name='repeat_interval_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cheesyquote',
            name='repeat_interval_weeks',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='compliment',
            name='repeat_interval_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compliment',
            name='repeat_interval_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compliment',
            name='repeat_interval_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compliment',
            name='repeat_interval_weeks',
            field=models.IntegerField(default=1),
        ),
    ]
