# Generated by Django 4.2.17 on 2025-03-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyserver_getcheesy', '0005_remove_cheesyjoke_repeat_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheesyjoke',
            name='repeat_interval_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cheesyjoke',
            name='repeat_interval_hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cheesyjoke',
            name='repeat_interval_minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cheesyjoke',
            name='repeat_interval_weeks',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cheesyquote',
            name='repeat_interval_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cheesyquote',
            name='repeat_interval_hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cheesyquote',
            name='repeat_interval_minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cheesyquote',
            name='repeat_interval_weeks',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='compliment',
            name='repeat_interval_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='compliment',
            name='repeat_interval_hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='compliment',
            name='repeat_interval_minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='compliment',
            name='repeat_interval_weeks',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
